

Ironstinger = int(12)
Aprentice_Rapier_ = int(13)
Crucible_Rapier = int(15)
Krystreza_ = int(15)
Canor_Fang_ = int(11)
Nemits_Sickle_ = int(10)
Tanto = int(15.5)
Krulian_Knife = int(12.5)
Flareblood_Kamas = int(16)
Iron_Cestus = int(13.5)
Legion_Cestus = int(15)
Flamekeeper_Cestus = int(15.5)
Messer = int(20)
Shotel = int(22)
Serpents_edge = int(22)
Shattered_katana = int(20)
Alloyed_Falchion = int(16)
Iron_Spear = int(17)
Ritual_Spear = int(19)
True_Seraphs_Spear = int(18.5)
Rifle_Spear = int(21)
Mace = int(20)
Sacred_Hammer = int(19.5)
Rosens_Peacemaker = int(18)
Iron_Blunderbuss = int(20)
Avenger = int(21)
Zweihander = int(22)
Darkalloy_Greatsword = int(26)
RailBlade = int(22)
Battleaxe = int(20)
Nightaxe = int(22)
Alloyed_Canorian_Axe = int(24)
Enforcers_Axe = int(26)
Steel_Maul = int(22)
Great_Maul = int(25)
Petras_Anchor = int(26)
Hivelords_Hubris = int(30)
SwordOfSlaves = int(100000000)

            